services:
  bedrock:
    image: debian:bookworm-slim                                                    # Use the latest Debian image 12.0
    init: true                                                                     # Use the init system
    labels:                                                                        # metadata for image
      - "com.robbeloth.family.description=Set up Minecraft Bedrock server"
      - "com.robbeloth.family.version=1.1"
    hostname: osr_bedrock                                                          # Custom host name for the container
    container_name: bedrock-container                                              # Do not use a random name
    environment:
      LD_LIBRARY_PATH: . ./bedrock_server
    ports:
      - 19132:19132/udp                                                            # Expose the bedrock port for Minecraft
    volumes:
      - "./data:/data"                                                             # Mount the data volume    
    stdin_open: true                                                               # Keep STDIN open even if not attached
    tty: true                                                                      # Allocate a pseudo-TTY
    command: >
      sh -c "mkdir -p bedrock &&
             cd bedrock &&
             apt-get update &&
             apt-get install -y wget &&
             apt-get install -y unzip &&
             apt-get install -y libcurl4 &&
             apt-get install -y libudev-dev && 
             apt-get install -y libudev0 &&
             apt-get install -y libudev1 &&
             wget --report-speed=bits -U \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36\" \"https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.31.04.zip\" &&
             unzip bedrock-server*.zip &&
             LD_LIBRARY_PATH=. ./bedrock_server"